# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Basic Airflow cluster configuration for CeleryExecutor with Redis and PostgreSQL.
#
# WARNING: This configuration is for local development. Do not use it in a production deployment.
#
# This configuration supports basic configuration using environment variables or an .env file
# The following variables are supported:
#
# AIRFLOW_IMAGE_NAME           - Docker image name used to run Airflow.
#                                Default: apache/airflow:3.0.0
# AIRFLOW_UID                  - User ID in Airflow containers
#                                Default: 50000
# AIRFLOW_PROJ_DIR             - Base path to which all the files will be volumed.
#                                Default: .
# Those configurations are useful mostly in case of standalone testing/running Airflow in test/try-out mode
#
# _AIRFLOW_WWW_USER_USERNAME   - Username for the administrator account (if requested).
#                                Default: airflow
# _AIRFLOW_WWW_USER_PASSWORD   - Password for the administrator account (if requested).
#                                Default: airflow
# _PIP_ADDITIONAL_REQUIREMENTS - Additional PIP requirements to add when starting all containers.
#                                Use this option ONLY for quick checks. Installing requirements at container
#                                startup is done EVERY TIME the service is started.
#                                A better way is to build a custom image or extend the official image
#                                as described in https://airflow.apache.org/docs/docker-stack/build.html.
#                                Default: ''
#
# Feel free to modify this file to suit your needs.
---
x-airflow-common:
  &airflow-common
  # In order to add custom dependencies or upgrade provider distributions you can use your extended image.
  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
  # image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:3.0.0}
  build: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

    ## to update the timezone where you live, update in .env file corresponding to the region u live
    AIRFLOW__CORE__DEFAULT_TIMEZONE: ${AIRFLOW__CORE__DEFAULT_TIMEZONE}

    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
    # yamllint disable rule:line-length
    # Use simple http server on scheduler for health checks
    # See https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/check-health.html#scheduler-health-check-server
    # yamllint enable rule:line-length
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    # WARNING: Use _PIP_ADDITIONAL_REQUIREMENTS option ONLY for a quick checks
    # for other purpose (development, test and especially production usage) build/extend Airflow image.
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
    # The following line can be used to set a custom config file, stored in the local config folder
    AIRFLOW_CONFIG: '/opt/airflow/config/airflow.cfg'
    SPARK_CONF_DIR: /opt/airflow/spark-conf

    HADOOP_CONF_DIR: /etc/hadoop/conf # for hadoop , so u can write in bash operator hdfs dfs directly as airflow communicate with hadoop
    DBT_PROFILES_DIR: /opt/airflow/dbt #for dbt

  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
    - ${AIRFLOW_PROJ_DIR:-.}/sparkJops:/opt/airflow/sparkJops  # for sparkJops to make bind mount from build context to airflow container
    - ${AIRFLOW_PROJ_DIR:-.}/data:/opt/spark-data  # to bindmount the data on localhost to here
    - ${AIRFLOW_PROJ_DIR:-.}/dbt:/opt/airflow/dbt  # to bindmount the dbt in buildcontext 
    - /var/run/docker.sock:/var/run/docker.sock    # airflow talks to docker deamon that runs the command since docker deamon is responsible for any command not airflow  >>> sudo chmod 666 /var/run/docker.sock in case of permissoin denied
    - ./hive_meta/conf/hive-site.xml:/opt/airflow/spark-conf/hive-site.xml  # seeing hive metastore
    - ./hadoop-conf:/etc/hadoop/conf # seeing all configuration of hadoop to write directly hdfs commands
    - ./data:/data
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:
  postgres:   # that is the host bro          to connect  psql -h localhost -U airflow -d airflow
    image: postgres:13
    environment:
      POSTGRES_USER: airflow  #  for login as user
      POSTGRES_PASSWORD: airflow # for password
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    ports:        # to expose on the localhost
      - "5432:5432"
    networks:
      - airflow  
  
  airflow-apiserver:
    <<: *airflow-common
    command: api-server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - airflow  

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    ports:
      - "5000:8080"  ## to bindmount docs from container on 8080 to be seen localhost with this port number if using net cat agent
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - airflow  

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - airflow  
  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - airflow  
  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    # yamllint disable rule:line-length
    command:
      - -c
      - |
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
          echo "If you are on Linux, you SHOULD follow the instructions below to set "
          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
          echo "For other operating systems you can get rid of the warning with manually created .env file:"
          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
          echo
          export AIRFLOW_UID=$(id -u)
        fi
        one_meg=1048576
        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
        disk_available=$$(df / | tail -1 | awk '{print $$4}')
        warning_resources="false"
        if (( mem_available < 4000 )) ; then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
          echo
          warning_resources="true"
        fi
        if (( cpus_available < 2 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
          echo "At least 2 CPUs recommended. You have $${cpus_available}"
          echo
          warning_resources="true"
        fi
        if (( disk_available < one_meg * 10 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
          echo
          warning_resources="true"
        fi
        if [[ $${warning_resources} == "true" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
          echo "Please follow the instructions to increase amount of resources available:"
          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
          echo
        fi
        echo
        echo "Creating missing opt dirs if missing:"
        echo
        mkdir -v -p /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Airflow version:"
        /entrypoint airflow version
        echo
        echo "Files in shared volumes:"
        echo
        ls -la /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Running airflow config list to create default config file if missing."
        echo
        /entrypoint airflow config list >/dev/null
        echo
        echo "Files in shared volumes:"
        echo
        ls -la /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Change ownership of files in /opt/airflow to ${AIRFLOW_UID}:0"
        echo
        chown -R "${AIRFLOW_UID}:0" /opt/airflow/
        echo
        echo "Change ownership of files in shared volumes to ${AIRFLOW_UID}:0"
        echo
        chown -v -R "${AIRFLOW_UID}:0" /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Files in shared volumes:"
        echo
        ls -la /opt/airflow/{logs,dags,plugins,config}

    # yamllint enable rule:line-length
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: 'apache-airflow[dataframes]==3.0.0 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-3.0.0/constraints-3.12.txt'
    user: "0:0"
    networks:
      - airflow  

  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
    command:
      - bash
      - -c
      - airflow
    depends_on:
      <<: *airflow-common-depends-on
    networks:
      - airflow  
  # You can enable flower by adding "--profile flower" option e.g. docker-compose --profile flower up
  # or by explicitly targeted on the command line e.g. docker-compose up flower.
  # See: https://docs.docker.com/compose/profiles/



  #         # Hive Metastore Database
  # hive-metastore:
  #   image: bde2020/hive:2.3.2-postgresql-metastore
  #   container_name: hive-metastore
  #   environment:
  #     - SERVICE=metastore
  #     - DB_DRIVER=postgres
  #     - DB_HOST=postgres         # we use postgres container 
  #     - DB_USER=hiveuser         # we must create hiveuser inside it + password=hivepassword and grant all privileges
  #     - DB_PASS=hivepassword
  #     - DB_NAME=hivemetastore
  #   volumes:
  #   - ./hive/hive-site.xml:/opt/hive/conf/hive-site.xml
  #   ports:
  #     - "9083:9083"
  #   networks:
  #     - airflow
  #   depends_on:
  #     - postgres

  # hive-server:
  #   image: bde2020/hive:2.3.2-postgresql-metastore
  #   container_name: hive-server
  #   environment:
  #     - SERVICE=hiveserver2
  #     - HIVE_METASTORE_URI=thrift://hive-metastore:9083
  #   ports:
  #     - "10000:10000"
  #   networks:
  #     - airflow
  #   depends_on:
  #     - hive-metastore
  # --------------------spark-----------
  
  # spark-master:
  #   image: bitnami/spark:3.3.0
  #   user: root
  #   environment:
  #     - SPARK_MODE=master
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #     - SPARK_MASTER_WEBUI_PORT=8081
  #     - HADOOP_CONF_DIR=/opt/bitnami/spark/conf/hadoop # to read from hdfs
  #   ports:
  #     - "8082:8081"
  #     - "7077:7077"
    
  #   volumes:
  #     - ./sparkJops:/opt/airflow/sparkJops  
  #     - ./hive_meta/conf/hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml  # bindmount to have metastore of hive
  #     - spark-data:/bitnami
  #     - ./apps:/opt/spark-apps
  #     - ./data:/opt/spark-data
  #     - ivy-cache:/root/.ivy2  #  when Spark downloads jars, they’re saved to your host machine (./ivy-cache), so we need to save them
  #     - ./hadoop-conf:/opt/bitnami/spark/conf/hadoop  # when enabled, u work with only hdfs not local host

  #                           # keep in mind use only data in hdfs only.!!!
  #                           #  bindmount to use hadoop hdfs without using # hdfs://namenode:8020, so u can use that hdfs://namenode:8020/staging_area/customers.csv or /staging_area/customers.csv
  #                           # if it is disabled u should use full path hdfs://namenode:8020/path or imagine you're in the spark conatiner like /opt/spark-data/path
  #                           # applying this also with worker & jupyter
  #   networks:
  #     - airflow
  #   # command: ["/opt/airflow/sparkJops/spark.sh"]

  # spark-worker:
  #   image: bitnami/spark:3.3.0
  #   user: root
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark-master:7077
  #     - SPARK_WORKER_MEMORY=2G
  #     - SPARK_WORKER_CORES=2
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #     - HADOOP_CONF_DIR=/opt/bitnami/spark/conf/hadoop # to read from hdfs
      
  #   volumes:
  #     - ./sparkJops:/opt/airflow/sparkJops  # u make map [current dir including docker compose, which test...]/sparkJops with that path of container
  #     - ./hive_meta/conf/hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml
  #     - spark-data:/bitnami
  #     - ./apps:/opt/spark-apps
  #     - ./data:/opt/spark-data
  #     - ivy-cache:/root/.ivy2 ##  when Spark downloads jars during spark-submit, they’re saved to your host machine (./ivy-cache), so we need to save them
  #     - ./hadoop-conf:/opt/bitnami/spark/conf/hadoop  # bindmount to use hadoop hdfs
      
  #   depends_on:
  #     - spark-master
  #   networks:
  #     - airflow  

    # command: ["/opt/airflow/sparkJops/spark.sh"]

  ## jupyter for spark ##


  # jupyter:
  #   image: jupyter/pyspark-notebook:latest
  #   container_name: jupyter-spark
  #   ports:
  #     - "8888:8888"

  #   environment:
  #     - JUPYTER_TOKEN=spark123  # Password for access
  #     - HIVE_METASTORE_URI=thrift://hive-metastore:9083  # for hive
  #     - SPARK_CONF_DIR=/home/jovyan/.spark-conf   # for hive
  #     - HADOOP_CONF_DIR=/opt/bitnami/spark/conf/hadoop  # to read from hdfs
  #   volumes:     # make /home/jovyan/name
  #     - ./notebooks:/home/jovyan/work  # Mount your notebooks directory
  #     - ./sparkJops:/home/jovyan/sparkJops  # Share Spark jobs with Airflow or seeing what u write in sparkJops created by sparkContainer
  #     - ./data:/home/jovyan/data  # Share data directory or seeing what make in data folder created by spark container
  #     - ./hive_meta/conf/hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml   # to mount to  thrift://hive-metastore:9083
  #     - ./hive_meta/conf/hive-site.xml:/home/jovyan/.spark-conf/hive-site.xml  # to mount to  thrift://hive-metastore:9083

  #     - ./hadoop-conf:/opt/bitnami/spark/conf/hadoop  #  bindmount using hdfs that allowing using only hdfs & u may stop to use local

  #   depends_on: 
  #     - spark-master
  #     - spark-worker
  #   networks:
  #     - airflow
  ##adding kafka ## 

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - airflow  
  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - airflow  

  schema-registry:
    image: confluentinc/cp-schema-registry:7.2.1
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
    networks:
      - airflow  


  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.2.1
    container_name: kafka-connect
    depends_on:
      - kafka
      # - schema-registry
    ports:
      - "8083:8083"
    environment:
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1      # Set to 1 to match number of brokers
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1      # Set to 1 to match number of brokers
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1      # Set to 1 to match number of brokers
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter # org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter # io.confluent.connect.avro.AvroConverter 
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "" #http://schema-registry:8081 [ we don't use schema registry]
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "" # http://schema-registry:8081 [ we don't use schema registry]
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars # it sees all connectors inside /etc/kafka-connect/jars
    volumes:
      - ./connectors:/etc/kafka-connect/jars  # you should make map from inside container to the build context, so any connector you need to install you should install inside connector
    networks:
      - airflow  

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: Assem
      MYSQL_PASSWORD: 123456789
    volumes:
    - mysql-data:/var/lib/mysql
    networks:
      - airflow  

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - airflow 


  # redis:
  #   image: redis/redis-stack-server:latest    # after opening the container, redis-cli to allow you to write commands >>> docker exec -it hast redis-cli instead of shell 
  #   container_name: redis-stack-server 
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379" # The standard Redis port
  #   networks:
  #     - redis-net
  #   volumes:
  #     - redis_data:/data

  # redis-insight:
  #   image: redislabs/redisinsight:latest
  #   container_name: redis-insight
  #   restart: unless-stopped
  #   ports:namenode
  #     - "8001:8001" # The RedisInsight web UI port
  #   networks:
  #     - redis-net
  #   depends_on:
  #     - redis

  # cassandra:
  #   image: cassandra:4.1
  #   container_name: cassandra
  #   ports:
  #     - "9042:9042"   # Cassandra CQL
  #   environment:
  #     - CASSANDRA_CLUSTER_NAME=SparkCluster
  #   healthcheck:
  #     test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #   volumes:
  #     - ./cassandra-init.cql:/init.cql   # preparation the container with tables after it is running up  
  #     - cassandra_data:/var/lib/cassandra  # persistent storage

  grafana:  # (dashboard for monitoring)
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER= 
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=hadesarchitect-cassandra-datasource
    volumes:
      - grafana-storage:/var/lib/grafana

    # networks:
      # - airflow
    network_mode: "host"  # allowing the container to use network of the host like >> like localhost:9090 inside the container  

# ================================
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - namenode:/hadoop/dfs/name
      - ./data:/data    # mount data on local device to namendoe to apply in it hdfs dfs -command
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hive_meta/hadoop-hive.env
    ports:
      - "50070:50070"
    networks:
      - airflow
    deploy:
      resources:
        limits:
          memory: 2g
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode:/hadoop/dfs/data
      - ./data:/data    # mount data on local device to namendoe to apply in it hdfs dfs -command
    env_file:
      - ./hive_meta/hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"
    networks:
      - airflow
    deploy:
      resources:
        limits:
          memory: 2g
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hive_meta/hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    networks:
      - airflow
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          memory: 2g

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hive_meta/hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    networks:
      - airflow
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          memory: 2g

  hive-metastore-postgresql:   # username & password is hive & hive and add in advanced settings port number 5433 since the default is 5432
    image: bde2020/hive-metastore-postgresql:2.3.0
    networks:
      - airflow
    ports:        # to expose on the localhost
      - "5433:5432"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          memory: 2g
    volumes:
    - hive-metastore-data:/var/lib/postgresql/data 

  nifi:
    image: apache/nifi:1.23.2
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: admin
      NIFI_WEB_HTTP_PORT: 8080
      NIFI_WEB_HTTPS_PORT: ''
    ports:
      - "8086:8080"
    volumes:
    
      - nifi_flow:/opt/nifi/nifi-current/flow
      - nifi_conf:/opt/nifi/nifi-current/conf
      - ./jdbc_drivers:/opt/nifi/nifi-current/jdbc
      - ./hadoop-conf:/opt/nifi/nifi-current/hadoop-conf  # to mount to hdfs 
      - ./data:/opt/spark-data
            # Hadoop Configuration Resources: for any processor in nifi
            #  /opt/nifi/nifi-current/hadoop-conf/core-site.xml,/opt/nifi/nifi-current/hadoop-conf/hdfs-site.xml
    depends_on:
      - namenode
      - datanode
    networks:
      - airflow
  
  # flume:
  #   build:
  #     context: .
  #     dockerfile: DockerFile.flume
  #   container_name: flume-agent
  #   volumes:
  #     - ./data:/data                    # For input data
  #     - ./flume-conf:/opt/flume/conf    # Custom configurations
  #     - ./hadoop-conf:/etc/hadoop/conf  # Hadoop configuration for HDFS
  #     - flume-logs:/var/log/flume
  #     - ./flume/plugins:/opt/flume/plugins  # For custom plugins if needed
  #   ports:
  #     - '44:44444'  # to bindmount netcat from container to localhost with this port number if using net cat agent
  #   environment:
  #     - HADOOP_CONF_DIR=/etc/hadoop/conf
  #     - FLUME_CONF_DIR=/opt/flume/conf
  #   depends_on:
  #     - namenode
  #     - datanode
  #   networks:
  #     - airflow
  #   command: >
  #     bash -c "
  #       cp /etc/hadoop/conf/* /opt/flume/conf/ &&
  #       /opt/flume/bin/flume-ng agent -n agent1 -c /opt/flume/conf -f /opt/flume/conf/flume.conf -Dflume.root.logger=INFO,console
  #     "
  #   restart: unless-stopped


  # Flink JobManager
  # =============================== docker exec faf flink run -py /opt/flink/python_jobs/kafka-python/flinkist_of_all.py
  # jobmanager:
  #   build:
  #     context: ./flink # Dockerfile here should install PyFlink + connectors
  #   ports:
  #     - "8087:8081" # Flink Web UI
  #   command: jobmanager
  #   environment:
  #     - |
  #       FLINK_PROPERTIES=
  #       jobmanager.rpc.address: jobmanager        
  #   volumes:
  #     # - ./flink/connectors:/opt/flink/lib  
  #     - ./flink/sql_jobs:/opt/flink/sql_jobs
  #     - ./flink/python_jobs:/opt/flink/python_jobs
  #     - ./connectors/flink-connector-jdbc-core-4.0.0-2.0.jar:/opt/flink/lib/flink-connector-jdbc-core-4.0.0-2.0.jar # connector for postsql
  #     - ./connectors/flink-connector-jdbc-postgres-4.0.0-2.0.jar:/opt/flink/lib/flink-connector-jdbc-postgres-4.0.0-2.0.jar
  #     - ./connectors/postgresql-42.7.3.jar:/opt/flink/lib/postgresql-42.7.3.jar
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1'
  #         memory: 1.5g
  #       reservations:
  #         cpus: '0.5'
  #         memory: 1g
  #   networks:
  #     - airflow
  # # # ===============================
  # # # Flink TaskManager
  # # # ===============================
  # taskmanager:
  #   build:
  #     context: ./flink
  #   depends_on:
  #     - jobmanager
  #   command: taskmanager
  #   environment:
  #     - |
  #       FLINK_PROPERTIES=
  #       jobmanager.rpc.address: jobmanager
  #       taskmanager.numberOfTaskSlots: 4 
  #   volumes:
  #     # - ./flink/connectors:/opt/flink/lib
  #     - ./flink/sql_jobs:/opt/flink/sql_jobs
  #     - ./flink/python_jobs:/opt/flink/python_jobs
  #     - ./connectors/flink-connector-jdbc-core-4.0.0-2.0.jar:/opt/flink/lib/flink-connector-jdbc-core-4.0.0-2.0.jar # connector for postsql
  #     - ./connectors/flink-connector-jdbc-postgres-4.0.0-2.0.jar:/opt/flink/lib/flink-connector-jdbc-postgres-4.0.0-2.0.jar
  #     - ./connectors/postgresql-42.7.3.jar:/opt/flink/lib/postgresql-42.7.3.jar


  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1'
  #         memory: 2g
  #       reservations:
  #         cpus: '0.5'
  #         memory: 1g
  #   networks:
  #     - airflow

volumes:
  postgres-db-volume:
  spark-data:
  mysql-data:
  ivy-cache:   # save all jars downloaded in persistent volume 
  redis_data:
  cassandra_data:
  grafana-storage:
  namenode:
  datanode:
  hive-metastore-data:
  nifi_flow:
  nifi_conf:
  flume-logs:

networks:
  airflow:
    driver: bridge
  redis-net:
    driver: bridge

        ## contecting from spark-master
# docker exec -it spark-master(hash) bash
# spark-sql --version  # should show Hive support
# spark-sql
# > show databases;

# set hive.metastore.uris;    # knowing url
# ------------------------------------
        ## contecting from hive-server
# docker exec -it hive-server(hash) hive 
  
