airflow_dbt_project:
  target: snowflake_dev   # you select one connection from here, maybe later you can change with postgres_dev
  
  outputs:
    postgres_dev:
    ## postgre connection
      type: postgres
      host: postgres
      user: airflow 
      pass: airflow
      port: 5432
      dbname: airflow
      schema: dbt_models
      threads: 1

    snowflake_dev:
    ## snowflake connection
      type: snowflake
      account: crelzlc-in80595 ##https://<this.value>.snowflakecomputing.com <<<< when clicking on url on outlook to activate the account
      user: MohamedAssem
      password: Qweasdzxc01019051187
      role: accountadmin
      database: GP
      warehouse: MY_WH
      schema: test
      threads: 2